name: namer_app
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 0.0.1+1

environment:
  sdk: '>=2.19.4 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  english_words: ^4.0.0
  provider: ^6.0.0
  logging: ^1.2.0
  http: ^1.1.0
  flutter_secure_storage: ^5.0.2
  shared_preferences: ^2.0.10
  crypto: ^3.0.2


dev_dependencies:
  flutter_test:
    sdk: flutter
  shared_preferences_web: ^2.0.0

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true